### ISSUE TITLE
All operations seem to be delayed

### ISSUE THREAD

**Issue by jrosetto** [vFense/vFense#212]
Just did a clean install and still having the same issue.  Even adding a customer doesn't show up until the next day.  Here is the setup I performed to get to this point.
-----------------------------------------

Ubuntu Server 12.04.5

rm -rf /var/lib/apt/lists/*

source /etc/lsb-release && echo "deb http://download.rethinkdb.com/apt $DISTRIB_CODENAME main" | sudo tee /etc/apt/sources.list.d/rethinkdb.list
wget -qO- https://download.rethinkdb.com/apt/pubkey.gpg | sudo apt-key add -
sudo apt-get update
sudo apt-get install -y rethinkdb=1.16.3~0precise

sudo apt-get install -y python-setuptools python-pip python-lxml python-pycurl python-redis python-openssl python-tornado python-beautifulsoup python-roman python-bcrypt python-ipaddr python-tz python-urlgrabber python-netifaces redis-server nginx-extras python-jsonpickle openssh-server python-simplejson patch git build-essential python-dev
sudo pip install --upgrade rq rethinkdb==1.16.0-4 requests apscheduler==2.1.2 tornado-redis xlrd roman six tornado python-dateutil

sudo git clone https://github.com/toppatch/vFense -b current /opt/TopPatch
sudo ln -s /opt/TopPatch/tp/src /usr/local/lib/python2.7/dist-packages/vFense

sudo python /opt/TopPatch/tp/src/scripts/initialize_vFense.py --ipaddress=192.168.5.195 --password=Everfit.2010

sudo service nginx restart
sudo service redis-server restart
sudo service rethinkdb restart
sudo python /opt/TopPatch/tp/src/daemon/vFensed start

-----------------------------------------
At the end of my install these errors come up which complain about the SSL which I haven't generated yet because I am evaluating the product first.  If this is my issue could someone let me know.
-----------------------------------------

  InsecurePlatformWarning
/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/ssl_.py:120: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
Traceback (most recent call last):
  File "/opt/TopPatch/tp/src/scripts/initialize_vFense.py", line 340, in <module>
    db_initialized, msg = initialize_db()
  File "/opt/TopPatch/tp/src/scripts/initialize_vFense.py", line 283, in initialize_db
    load_up_all_xml_into_db()
  File "/usr/local/lib/python2.7/dist-packages/vFense/plugins/vuln/cve/parser.py", line 366, in load_up_all_xml_into_db
    parse_cve_and_udpatedb(False, nvd_files)
  File "/usr/local/lib/python2.7/dist-packages/vFense/plugins/vuln/cve/parser.py", line 314, in parse_cve_and_udpatedb
    for event, entry in etree.iterparse(nvd_file, events=['start', 'end']):
  File "iterparse.pxi", line 478, in lxml.etree.iterparse.__next__ (src/lxml/lxml.etree.c:98432)
  File "iterparse.pxi", line 530, in lxml.etree.iterparse._read_more_events (src/lxml/lxml.etree.c:98953)
  File "parser.pxi", line 590, in lxml.etree._raiseParseError (src/lxml/lxml.etree.c:74696)
lxml.etree.XMLSyntaxError: EntityRef: expecting ';', line 9, column 109

-----------------------------------------
Also after vFense was running on the server I saw this which could also be an issue.
-----------------------------------------

Traceback (most recent call last):
  File "src/scheduler/rvscheduler.py", line 17, in <module>
    get_supported_apps()
  File "/usr/local/lib/python2.7/dist-packages/vFense/plugins/patching/apps/supported_apps/syncer.py", line 366, in get_supported_apps
    os.path.join(BASE_URL, GET_SUPPORTED_UPDATES)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 67, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 53, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 437, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='updater2.toppatch.com', port=80): Max retries exceeded with url: /api/new_updater/pkglist (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x1ea0590>: Failed to establish a new connection: [Errno 110] Connection timed out',))

**Comment by jrosetto** [comment]
Just did a clean install and still having the same issue.  Even adding a customer doesn't show up until the next day.  Here is the setup I performed to get to this point.

Ubuntu Server 12.04.5

rm -rf /var/lib/apt/lists/*

source /etc/lsb-release && echo "deb http://download.rethinkdb.com/apt $DISTRIB_CODENAME main" | sudo tee /etc/apt/sources.list.d/rethinkdb.list
wget -qO- https://download.rethinkdb.com/apt/pubkey.gpg | sudo apt-key add -
sudo apt-get update
sudo apt-get install -y rethinkdb=1.16.3~0precise

sudo apt-get install -y python-setuptools python-pip python-lxml python-pycurl python-redis python-openssl python-tornado python-beautifulsoup python-roman python-bcrypt python-ipaddr python-tz python-urlgrabber python-netifaces redis-server nginx-extras python-jsonpickle openssh-server python-simplejson patch git build-essential python-dev
sudo pip install --upgrade rq rethinkdb==1.16.0-4 requests apscheduler==2.1.2 tornado-redis xlrd roman six tornado python-dateutil

sudo git clone https://github.com/toppatch/vFense -b current /opt/TopPatch
sudo ln -s /opt/TopPatch/tp/src /usr/local/lib/python2.7/dist-packages/vFense

sudo python /opt/TopPatch/tp/src/scripts/initialize_vFense.py --ipaddress=192.168.5.195 --password=Everfit.2010

sudo service nginx restart
sudo service redis-server restart
sudo service rethinkdb restart
sudo python /opt/TopPatch/tp/src/daemon/vFensed start

At the end of my install these errors come up which complain about the SSL which I haven't generated yet because I am evaluating the product first.  If this is my issue could someone let me know.

  InsecurePlatformWarning
/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/ssl_.py:120: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
Traceback (most recent call last):
  File "/opt/TopPatch/tp/src/scripts/initialize_vFense.py", line 340, in <module>
    db_initialized, msg = initialize_db()
  File "/opt/TopPatch/tp/src/scripts/initialize_vFense.py", line 283, in initialize_db
    load_up_all_xml_into_db()
  File "/usr/local/lib/python2.7/dist-packages/vFense/plugins/vuln/cve/parser.py", line 366, in load_up_all_xml_into_db
    parse_cve_and_udpatedb(False, nvd_files)
  File "/usr/local/lib/python2.7/dist-packages/vFense/plugins/vuln/cve/parser.py", line 314, in parse_cve_and_udpatedb
    for event, entry in etree.iterparse(nvd_file, events=['start', 'end']):
  File "iterparse.pxi", line 478, in lxml.etree.iterparse.__next__ (src/lxml/lxml.etree.c:98432)
  File "iterparse.pxi", line 530, in lxml.etree.iterparse._read_more_events (src/lxml/lxml.etree.c:98953)
  File "parser.pxi", line 590, in lxml.etree._raiseParseError (src/lxml/lxml.etree.c:74696)
lxml.etree.XMLSyntaxError: EntityRef: expecting ';', line 9, column 109

Also after vFense was running on the server I saw this which could also be an issue.

Traceback (most recent call last):
  File "src/scheduler/rvscheduler.py", line 17, in <module>
    get_supported_apps()
  File "/usr/local/lib/python2.7/dist-packages/vFense/plugins/patching/apps/supported_apps/syncer.py", line 366, in get_supported_apps
    os.path.join(BASE_URL, GET_SUPPORTED_UPDATES)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 67, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 53, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 437, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='updater2.toppatch.com', port=80): Max retries exceeded with url: /api/new_updater/pkglist (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x1ea0590>: Failed to establish a new connection: [Errno 110] Connection timed out',))

**Comment by jrosetto** [comment]
Can I assume this project is dead?

**Comment by linuxdynasty** [comment]
Good morning @jrosetto. You are correct, the project is dead. No one has worked on it for over a year now. I was the last one trying to keep it up and make it into the best open source patch management project. I finally realized, I can no longer do this on my own. I was hoping that someone in the community would fork it or even help me out, but that did not happen.

**Comment by jrosetto** [comment]
It's a shame all the hard work and time is going to waste but as I don't have the time to invest in the project I can understand where you are coming from.  Thanks for the contribution anyway.  Can you recommend anything else that would do basically the same job as this project that is still free (not WSUS)?  I stumbled upon this thinking I struck gold but it would appear it was to go to be true.

**Comment by jlk** [comment]
Personally, I'm resistant to calling it "dead." I'm not aware of another open source patch management platform like this - it's something I wanted for many years. I was starting to work on it a while back, but ran out of time. Hoping a project I'm working on this year will again give me reason to carve out time to work on it.

Help get the word out wherever you can - I try to mention vFense when patch management topics come up in conversation. Really hoping this can turn the corner and turn into something that more folks actively use and contribute to!

**Comment by linuxdynasty** [comment]
Believe you me, I really want to see this successful. I can get the server and the unix agent where it needs to be, but I need UI help. If the open source community/companies want to assist me into making this project the best open source patch management system out there, than I am all in. :D. @jlk, I will see you in San Francisco between February 21st and the 27th.

**Comment by linuxdynasty** [comment]
I'm willing to give this another shot @jrosetto. This project is bigger than one person, so any assistance is welcome.

**Comment by jrosetto** [comment]
I'm not apposed to working on it in the little free time I have.  Can you elaborate more on what you are looking for when you say UI help?  I see the documentation could be updated being outdated which I could update.  Also could create a virtual appliance to get people with limited Linux knowledge up and running quickly to spread interest for the drive by browser users.

**Comment by jlk** [comment]
+1 on that last point...something I was looking for in the last few weeks was a working container image of vFense so I could spin it up quickly to test some things out. Saw a few accounts on docker hub had started trying to do vFense images, haven't found a successful one, yet...

**Comment by linuxdynasty** [comment]
So I was able to wrangle up some of the original developers of vFense and we are all willing to give this a 2nd run. We are going to update the API documentation and see if we can get the current server up and running again.

**Comment by jrosetto** [comment]
Awesome!  If I can provide any assistance let me know.

**Comment by linuxdynasty** [comment]
@jrosetto I updated the install documentation, so that the correct version of RethinkDB is installed as well as the correct version of Nginx and the correct version of the Python RethinkDB module. I just ran an install following the instructions and all is working with a Linux Agent. Sorry, I do not have a windows system to test a windows agent.

**Comment by jrosetto** [comment]
Sounds good.  I have to finish a server install then I can tests a windows agent for you.

**Comment by jrosetto** [comment]
Sill waiting on the agents to show up in the interface.  How long does it generally take and is the agent compatible with Windows 10?  I have an agent on 7, 10, and Debian right now.

**Comment by jrosetto** [comment]
All agent's displayed in the web interface.  I started an operation to install updates on the Windows 7 box and am waiting for it to actually take effect.  Still having huge delays with everything.

**Comment by linuxdynasty** [comment]
What about installing on the debian agent, does that also take a while?  I can help you debug with the Unix Agents, but maybe @ddelapaz can help you debug with the Windows agent

**Comment by jrosetto** [comment]
Yup all the agents took about a day to show up.  I tried to push the updates but haven't seen anything in operations yet.

**Comment by jrosetto** [comment]
Pretty sure it is an issue with the server and not the agent.  Even deleting one of the agents takes an excessive amount of time.  I deleted one of the agents from the dashboard about 30 minutes ago and it still hasn't disappeared.  Which log files would you like?  Do you prefer pastebin or posting directly?

**Comment by ddelapaz** [comment]
@jrosetto Please send me the log file for the agent(s) on the windows system. You can just pastebin and provide url here. Thanks!

**Comment by jrosetto** [comment]
I manually told it to install 1 update under the agent.  Also when installing the agent it will not verify the credentials which I am sure are correct as I use the same credentials to login to the web interface.

[http://pastebin.com/vkjuTWJc](url)

Let me know,

Thanks.

**Comment by ddelapaz** [comment]
@jrosetto The log ends in the agent populating a list of updates, do you have any additional log files after that particular one that you sent me? If possible, zip up the entire log folder and email it to me directly at ddelap01@gmail.com

**Comment by jrosetto** [comment]
@ddelapaz email sent.

**Comment by ddelapaz** [comment]
@jrosetto Thank you, what branch did you use for the windows agent, Master?

**Comment by jrosetto** [comment]
Compiled TopPatchAgent2013 and used the setup.aip in the AI Projects directory.

**Comment by jrosetto** [comment]
It's early...  Yes I used master.

**Comment by jrosetto** [comment]
I did finally get an error in the web interface under Operations.  It says 'ttl expired.'

**Comment by jrosetto** [comment]
@ddelapaz any update on the issue?

**Comment by linuxdynasty** [comment]
@jrosetto , I think @ddelapaz is going to need some more time, as this for all of us is a side project. I am also working with him on trying to figure this out on my free time as well.

**Comment by jrosetto** [comment]
No worries.  Not trying to be a PITA, just checking in.  Again thanks for taking the time, it is greatly appreciated.

**Comment by linuxdynasty** [comment]
@jrosetto I merged the fix for the no_reply error in the current branch. This will fix the updating of the monit stats, which is what the error log shows.

**Comment by ddelapaz** [comment]
@jrosetto No worries, I will be looking into a fix this weekend and will Update as soon as we get something going in regards to those agent's taking so long to show results. Thank you though :+1:

**Comment by jrosetto** [comment]
You guys really need to find more freetime :)

**Comment by linuxdynasty** [comment]
@jrosetto have you tried since my last reply?

**Comment by jrosetto** [comment]
I did try after your reply.  The monitoring stats update now but I am still having issues pushing the updates.  Keep getting ttl error's.

**Comment by jrosetto** [comment]
I decided to set everything up from scratch again.  Installed the server, recompiled the client.  This is what I came up with.

Pushing updates from the server to the client seems to work reasonably well.  All my issues seem to be related to the web interface not updating in a timely fashion.  After pushing the update I see in the client log that the update was installed and over an hour later the web interface still hasn't updated to reflect that the client performed the operation.  I also found that if Windows Updates was set to disabled the client flat out wouldn't work.

The only other odd thing that I noticed was after 3 hours after sending a shutdown from the web interface it is still pending under operations.  The computer shutdown fine and has since been turned back on and the agent is active.

BTW I am running these test on a Windows 10 client and it seems to be cooperating.

Any suggestions on the web interface?
